---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/name: openstack-lightspeed-operator
    app.kubernetes.io/managed-by: kustomize
  name: openstack-config-reader-binding
  namespace: openstack
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: openstack-config-reader
subjects:
- kind: ServiceAccount
  name: controller-manager
  namespace: system
